### ISSUE TITLE
Threshold for colour merging?

### ISSUE THREAD

**Issue by robincafolla** [meyerweb/px2svg#2]
Should we add a second parameter threshold to allow colour compression? Similar colours, maybe based on hue, could be merged based on the supplied threshold value. That should lead to reduced file sizes.

I don't mind giving this a shot over the weekend if it's something worth adding.

**Comment by meyerweb** [comment]
I’m okay with it as an option, as long as the default is no merging.

**Comment by robincafolla** [comment]
Certainly.
